---
title: "YaYasso"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{YaYasso}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


The package depends on the package [`SoilR`](http://dirk.eddelbuettel.com/code/drat.html), which is automatically loaded when `YaYasso` is loaded.

```{r}
library(YaYasso)
```
After having loaded the main library, we create the input data required:

```{r}
years=seq(from=1,to=10,by=1)#/365)
Litter=data.frame(year=c(1:10),Litter=rnorm(n=10,mean=10,sd=2))
TempData=data.frame(years,Temp=15+sin(2*pi*years)+
                      rnorm(n=length(years),mean=0,sd=1))
j=length(years) # how many years we simulate
MeanTemperature <- TempData$Temp
TemperatureAmplitude <- rep(diff(range(TempData[,2]))/2,j) # temperature amplitude
Precipitation <- rep(800,j) # precipitation 800mm

MT=MeanTemperature
TA=TemperatureAmplitude
PR_mm=Precipitation
#note conversion from mm to meters in the model's environmental function
```

We can now run a basic simulation with these data:
```{r}
# EXAMPLE of fixed model ##
# Modified yasso07 C. Sierra general model WITH environmental effect
yassofix <- Yasso07.Modelfi(years,
                           C0=rep(0,5), #initial carbon
                           AWEN = c(0.52,0.18,0.08,0.2,0), #to separate litter to yasso AWEN pools, this depends on plant organ and species
                           In=Litter,#litter C input (same length as years)
                           xi = T, # xi = F  will replace climate data no climate effect,
                           MT=MT,#MeanTemperature
                           TA=TA, #TemperatureAmplitude
                           PR_mm=PR_mm,#Precipitation_mm)
                           WS=2)

Ct = getC(yassofix)
Rt = getReleaseFlux(yassofix) #respiration

```
```{r}
#plot carbon pools
matplot( Ct, type="l", lty=1, col=1:5, xlab="Years", ylab="Carbon stocks", main ="YM07fix(envir.)")
legend("topleft", c("A","W","E","N", "H"), lty=1, col=1:5, bty="n", n = 2)

```

```{r}
#plot respiration
matplot(years, Rt, type="l", ylab="Respiration", lty=1, col=1:2)
```

